DELETE http://localhost:3001/api/persons/604748ee6751132cbc4f1c6f

###

GET http://localhost:3001/api/persons/60464c83f3fa2525401a997e

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "dan",
    "number": "053-8459228"
}