DELETE http://localhost:3001/api/persons/60464c64f3fa2525401a997d

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "asd",
    "number": "053-8945923"
}